// yoann.croguennec@gmail.com
import type { Metadata } from "next";
import "./globals.css";
import { auth, signOut } from "@/auth/authSetup";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  console.log("====================================");
  console.log(session?.user?.email);
  console.log("====================================");
  return (
    <html lang='en'>
      <body cz-shortcut-listen='true'>
        <div className='hover:underline'>
          {session?.user ? (
            <form
              action={async () => {
                "use server";
                await signOut();
              }}
            >
              <div className='flex items-center gap-2'>
                <button>Logout</button>
              </div>
            </form>
          ) : (
            <Link href='/login'>Login</Link>
          )}
        </div>
        <div>
          {session?.user?.email ? (
            <h1>{session?.user?.email}</h1>
          ) : (
            <h1>Pas connecté</h1>
          )}{" "}
        </div>
        {children}
      </body>
    </html>
  );
}
